#the first spec is for replicaset which makes sure we have the same number of pods that we specify
#and the second spec is for the pod specification #i changed the manifest to deployment
apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: nginx-deploy
  labels: 
    env: demo 
spec: 
  template: 
    metadata: 
      labels: 
        env: demo 
      name: nginx 
    spec: 
      containers: 
      - image: nginx
        name: nginx  
  replicas: 3      
  selector:
    matchLabels:
      env: demo
      

  